[package]
name = "psh-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
perf-event-rs.workspace = true
prost.workspace = true
serde = { workspace = true, features = ["derive"] }
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
